[package]
name = "esp-node"
publish = false
edition = "2024"

# Don't include this project in the workspace above it
[workspace]

[dependencies]
# Local
zencan-node = { path = "../../zencan-node", default-features = false, features = ["log"] }

# External
esp-bootloader-esp-idf = "0.5.0"
esp-hal = { version = "~1.1.0", features = ["unstable"] }
esp-rtos = { version = "0.3.0", features = ["embassy"] }
esp-println = { version = "0.17.0", features = ["log-04"] }
esp-backtrace = { version = "0.19.0", features = [
  "panic-handler",
  "println",
] }
embassy-executor = "0.10.0"
embassy-futures = "0.1.2"
embassy-time = "0.5.1"
embassy-sync = "0.8.0"
embedded-can = "0.4.1"
log = "0.4.33"

[features]
esp32c3 = [
  "esp-bootloader-esp-idf/esp32c3",
  "esp-hal/esp32c3",
  "esp-rtos/esp32c3",
  "esp-println/esp32c3",
  "esp-backtrace/esp32c3"
]
esp32c6 = [
  "esp-bootloader-esp-idf/esp32c6",
  "esp-hal/esp32c6",
  "esp-rtos/esp32c6",
  "esp-println/esp32c6",
  "esp-backtrace/esp32c6"
]

[build-dependencies]
zencan-build = { path = "../../zencan-build" }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = true
opt-level = "s"
overflow-checks = false
