name: Rust Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --examples --verbose
      - name: Build esp-node example
        working-directory: examples/esp-node
        run: cargo build --target riscv32imc-unknown-none-elf --features esp32c3
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Clippy Examples
        run: cargo clippy --examples -- -D warnings
      - name: rustfmt
        run: cargo fmt --check
      - name: Run tests
        run: cargo test --verbose
      - name: Build stm32g0-lilos-node example
        working-directory: examples/stm32g0-lilos-node
        run: cargo build
